# Auto-generated by scripts/generate_stubs.py — do not edit manually.
from collections.abc import Awaitable, Callable, Coroutine
from typing import Any, overload

# --- 0 parameters ---
@overload
def awaitify[R](
    func: Callable[[], Coroutine[Any, Any, R]],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[[], Coroutine[Any, Any, R]]: ...

@overload
def awaitify[R](
    func: Callable[[], R],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[[], Coroutine[Any, Any, R]]: ...

# --- 1 parameter ---
@overload
def awaitify[T1, R](
    func: Callable[[T1], Coroutine[Any, Any, R]],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[[T1 | Awaitable[T1]], Coroutine[Any, Any, R]]: ...

@overload
def awaitify[T1, R](
    func: Callable[[T1], R],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[[T1 | Awaitable[T1]], Coroutine[Any, Any, R]]: ...

# --- 2 parameters ---
@overload
def awaitify[T1, T2, R](
    func: Callable[[T1, T2], Coroutine[Any, Any, R]],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[[T1 | Awaitable[T1], T2 | Awaitable[T2]], Coroutine[Any, Any, R]]: ...

@overload
def awaitify[T1, T2, R](
    func: Callable[[T1, T2], R],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[[T1 | Awaitable[T1], T2 | Awaitable[T2]], Coroutine[Any, Any, R]]: ...

# --- 3 parameters ---
@overload
def awaitify[T1, T2, T3, R](
    func: Callable[[T1, T2, T3], Coroutine[Any, Any, R]],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[[T1 | Awaitable[T1], T2 | Awaitable[T2], T3 | Awaitable[T3]], Coroutine[Any, Any, R]]: ...

@overload
def awaitify[T1, T2, T3, R](
    func: Callable[[T1, T2, T3], R],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[[T1 | Awaitable[T1], T2 | Awaitable[T2], T3 | Awaitable[T3]], Coroutine[Any, Any, R]]: ...

# --- 4 parameters ---
@overload
def awaitify[T1, T2, T3, T4, R](
    func: Callable[[T1, T2, T3, T4], Coroutine[Any, Any, R]],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
    ],
    Coroutine[Any, Any, R],
]: ...

@overload
def awaitify[T1, T2, T3, T4, R](
    func: Callable[[T1, T2, T3, T4], R],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
    ],
    Coroutine[Any, Any, R],
]: ...

# --- 5 parameters ---
@overload
def awaitify[T1, T2, T3, T4, T5, R](
    func: Callable[[T1, T2, T3, T4, T5], Coroutine[Any, Any, R]],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
        T5 | Awaitable[T5],
    ],
    Coroutine[Any, Any, R],
]: ...

@overload
def awaitify[T1, T2, T3, T4, T5, R](
    func: Callable[[T1, T2, T3, T4, T5], R],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
        T5 | Awaitable[T5],
    ],
    Coroutine[Any, Any, R],
]: ...

# --- 6 parameters ---
@overload
def awaitify[T1, T2, T3, T4, T5, T6, R](
    func: Callable[[T1, T2, T3, T4, T5, T6], Coroutine[Any, Any, R]],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
        T5 | Awaitable[T5],
        T6 | Awaitable[T6],
    ],
    Coroutine[Any, Any, R],
]: ...

@overload
def awaitify[T1, T2, T3, T4, T5, T6, R](
    func: Callable[[T1, T2, T3, T4, T5, T6], R],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
        T5 | Awaitable[T5],
        T6 | Awaitable[T6],
    ],
    Coroutine[Any, Any, R],
]: ...

# --- 7 parameters ---
@overload
def awaitify[T1, T2, T3, T4, T5, T6, T7, R](
    func: Callable[[T1, T2, T3, T4, T5, T6, T7], Coroutine[Any, Any, R]],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
        T5 | Awaitable[T5],
        T6 | Awaitable[T6],
        T7 | Awaitable[T7],
    ],
    Coroutine[Any, Any, R],
]: ...

@overload
def awaitify[T1, T2, T3, T4, T5, T6, T7, R](
    func: Callable[[T1, T2, T3, T4, T5, T6, T7], R],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
        T5 | Awaitable[T5],
        T6 | Awaitable[T6],
        T7 | Awaitable[T7],
    ],
    Coroutine[Any, Any, R],
]: ...

# --- 8 parameters ---
@overload
def awaitify[T1, T2, T3, T4, T5, T6, T7, T8, R](
    func: Callable[[T1, T2, T3, T4, T5, T6, T7, T8], Coroutine[Any, Any, R]],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
        T5 | Awaitable[T5],
        T6 | Awaitable[T6],
        T7 | Awaitable[T7],
        T8 | Awaitable[T8],
    ],
    Coroutine[Any, Any, R],
]: ...

@overload
def awaitify[T1, T2, T3, T4, T5, T6, T7, T8, R](
    func: Callable[[T1, T2, T3, T4, T5, T6, T7, T8], R],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
        T5 | Awaitable[T5],
        T6 | Awaitable[T6],
        T7 | Awaitable[T7],
        T8 | Awaitable[T8],
    ],
    Coroutine[Any, Any, R],
]: ...

# --- 9 parameters ---
@overload
def awaitify[T1, T2, T3, T4, T5, T6, T7, T8, T9, R](
    func: Callable[[T1, T2, T3, T4, T5, T6, T7, T8, T9], Coroutine[Any, Any, R]],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
        T5 | Awaitable[T5],
        T6 | Awaitable[T6],
        T7 | Awaitable[T7],
        T8 | Awaitable[T8],
        T9 | Awaitable[T9],
    ],
    Coroutine[Any, Any, R],
]: ...

@overload
def awaitify[T1, T2, T3, T4, T5, T6, T7, T8, T9, R](
    func: Callable[[T1, T2, T3, T4, T5, T6, T7, T8, T9], R],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
        T5 | Awaitable[T5],
        T6 | Awaitable[T6],
        T7 | Awaitable[T7],
        T8 | Awaitable[T8],
        T9 | Awaitable[T9],
    ],
    Coroutine[Any, Any, R],
]: ...

# --- 10 parameters ---
@overload
def awaitify[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R](
    func: Callable[[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10], Coroutine[Any, Any, R]],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
        T5 | Awaitable[T5],
        T6 | Awaitable[T6],
        T7 | Awaitable[T7],
        T8 | Awaitable[T8],
        T9 | Awaitable[T9],
        T10 | Awaitable[T10],
    ],
    Coroutine[Any, Any, R],
]: ...

@overload
def awaitify[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R](
    func: Callable[[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10], R],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[
    [
        T1 | Awaitable[T1],
        T2 | Awaitable[T2],
        T3 | Awaitable[T3],
        T4 | Awaitable[T4],
        T5 | Awaitable[T5],
        T6 | Awaitable[T6],
        T7 | Awaitable[T7],
        T8 | Awaitable[T8],
        T9 | Awaitable[T9],
        T10 | Awaitable[T10],
    ],
    Coroutine[Any, Any, R],
]: ...

# --- fallback ---
@overload
def awaitify(
    func: Callable[..., Any],
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Callable[..., Coroutine[Any, Any, Any]]: ...

def awaitify(
    func: Any,
    /,
    *wait_for: Awaitable[Any],
    track: bool = ...,
    auto_progress: bool = ...,
) -> Any: ...
